MxOnline/urls.py
from django.contrib import admin
from django.conf.urls import url, include
import xadmin
from django.views.generic import TemplateView
from users.views import *
from MxOnline.settings import MEDIA_ROOT
from django.views.static import serve

urlpatterns = [
    url(r'xadmin/', xadmin.site.urls),
    url(r'^$', TemplateView.as_view(template_name='index.html'), name='index'),
    url(r'login/$', LoginView.as_view(), name='login'),
    url(r'register/$', RegisterView.as_view(), name='register '),
    url(r'captcha/', include('captcha.urls')),
    url(r'active/(?P<active_code>.*)/$', ActiveUserView.as_view(), name='active'),
    url(r'forget/$', ForgetPwdView.as_view(), name='forget'),
    url(r'reset/(?P<active_code>.*)/$', ResetView.as_view(), name='reset'),
    url(r'^modify_pwd/$', ModifyPwdView.as_view(), name="modify_pwd"),
    url(r'^media/(?P<path>.*)$', serve, {"document_root": MEDIA_ROOT}),

    url(r'^org/', include('organization.urls', namespace='org')),
    url(r'^course/', include('courses.urls', namespace='course'))
]

apps/courses/urls.py
from django.conf.urls import url, include
from .views import *

urlpatterns = [
    url(r'course_list/$', CourseListView.as_view(), name='course_list'),
    url(r'course_detail/(?P<course_id>\d+)', CourseDetailView.as_view(), name='course_detail'),
]

apps/organization/urls.py
from django.conf.urls import url, include
from .views import *

urlpatterns = [
    url(r'list/$', OrganizationView.as_view(), name='org_list'),
    url(r'add_ask/$', UserAskView.as_view(), name='add_ask'),
    url(r'detail/(?P<org_id>\d+)/$', OrgDetailHomeView.as_view(), name='detail'),
    url(r'course/(?P<org_id>\d+)/$', OrgDetailCourseView.as_view(), name='org_course'),
    url(r'desc/(?P<org_id>\d+)/$', OrgDetailDescView.as_view(), name='org_desc'),
    url(r'teacher/(?P<org_id>\d+)/$', OrgDetailTeacherView.as_view(), name='org_teacher'),

    url(r'add_fav/$', AddFavView.as_view(), name='add_fav')
]

apps/courses/models.py
from django.db import models
from datetime import datetime
from organization.models import *


# Create your models here.
class Course(models.Model):
    course_org = models.ForeignKey(CourseOrg, verbose_name='机构', on_delete=models.CASCADE)
    name = models.CharField(max_length=50, null=True, blank=True, verbose_name='课程名称')
    desc = models.CharField(max_length=300, verbose_name='简介')
    detail = models.TextField(verbose_name='课程详情')
    is_banner = models.BooleanField(default=False, verbose_name='是否轮播图')
    teacher = models.ForeignKey(Teacher, verbose_name='教师', on_delete=models.CASCADE)
    degree = models.CharField(verbose_name='难度', choices=(('easy', '初级'), ('normal', '普通'), ('hard', '困难')),
                              max_length=10, default='easy')
    learn_times = models.IntegerField(default=0, verbose_name='学习时长（分钟）')
    students = models.IntegerField(default=0, verbose_name='学习人数')
    fav_nums = models.IntegerField(default=0, verbose_name='点赞数')
    image = models.ImageField(upload_to='course/%Y/%m', verbose_name='封面图', max_length=100,
                              default='course/default.png')
    click_nums = models.IntegerField(default=0, verbose_name='点击数')
    category = models.CharField(max_length=50, verbose_name='类别', default='')
    tag = models.CharField(max_length=50, verbose_name='标签', default='')
    youneed_know = models.CharField(verbose_name='课程须知', max_length=300, default='')
    teacher_tell = models.CharField(verbose_name='老师告诉你', max_length=300, default='')
    add_time = models.DateTimeField(verbose_name='添加时间', default=datetime.now)

    class Meta():
        verbose_name = '课程'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class Lesson(models.Model):
    course = models.ForeignKey(Course, verbose_name='课程', on_delete=models.CASCADE)
    name = models.CharField(max_length=50, verbose_name='章节名称')
    learn_time = models.IntegerField(default=0, verbose_name='学习时间')
    add_time = models.DateTimeField(default=datetime.now, verbose_name='添加时间')

    class Meta():
        verbose_name = '章节'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class Video(models.Model):
    lesson = models.ForeignKey(Lesson, verbose_name='课程', on_delete=models.CASCADE)
    name = models.CharField(max_length=20, default='', verbose_name='名称')
    learn_time = models.IntegerField(default=0, verbose_name='学时时长')
    url = models.CharField(max_length=200, verbose_name='访问地址', default='')
    add_time = models.DateTimeField(default=datetime.now, verbose_name='添加时间')

    class Meta():
        verbose_name = '视频'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class CourseResource(models.Model):
    course = models.ForeignKey(Course, verbose_name='课程', on_delete=models.CASCADE)
    name = models.CharField(max_length=20, default='', verbose_name='名称')
    download = models.FileField(upload_to='video/%Y/%m', verbose_name='资源文件', max_length=200)
    add_time = models.DateTimeField(default=datetime.now, verbose_name='添加时间')

    class Meta():
        verbose_name = '课程资源'
        verbose_name_plural = verbose_name

apps/organization/models.py
from django.db import models


# Create your models here.
class CityDict(models.Model):
    name = models.CharField(max_length=20, verbose_name='城市')
    desc = models.CharField(max_length=200, verbose_name='描述')
    add_time = models.DateTimeField(default='', verbose_name='添加时间')

    class Meta():
        verbose_name = '城市信息'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class CourseOrg(models.Model):
    name = models.CharField(max_length=20, default='', verbose_name='机构名称')
    desc = models.TextField(default='', verbose_name='机构描述')
    tag = models.CharField(max_length=50, default='', verbose_name='标签')
    category = models.CharField(max_length=20, default='gr', verbose_name='机构类别',
                                choices=(('pxjg', '培训机构'), ('gr', '个人'), ('gx', '高校')))
    click_nums = models.IntegerField(default=0, verbose_name='点击数')
    fav_nums = models.IntegerField(default=0, verbose_name='收藏数')
    image = models.ImageField(default='org/default.png', upload_to='org/%Y/%m', verbose_name='封面图')
    address = models.ForeignKey(CityDict, verbose_name='所在城市', on_delete=models.CASCADE)
    students = models.IntegerField(default=0, verbose_name='学习人数')
    course_nums = models.IntegerField(default=0, verbose_name='课程数')
    add_time = models.DateTimeField(default='', verbose_name='添加时间')

    class Meta():
        verbose_name = '课程机构'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class Teacher(models.Model):
    org = models.ForeignKey(CourseOrg, verbose_name='归属机构', on_delete=models.CASCADE)
    name = models.CharField(max_length=20, default='', verbose_name='教师姓名')
    work_years = models.IntegerField(default=0, verbose_name='工作年限')
    work_company = models.CharField(max_length=50, verbose_name='工作单位', default='')
    work_position = models.CharField(max_length=50, verbose_name='工作职位', default='')
    points = models.CharField(max_length=200, verbose_name='特色', default='')
    click_nums = models.IntegerField(default=0, verbose_name='点击数')
    fav_nums = models.IntegerField(default=0, verbose_name='收藏数')
    age = models.IntegerField(default=0, verbose_name='年龄')
    image = models.ImageField(upload_to='', default='', verbose_name='头像')
    add_time = models.DateTimeField(default='', verbose_name='添加时间')

    class Meta():
        verbose_name = '教师'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name

apps/organization/forms.py
from django import forms
from operation.models import UserAsk
import re


class UserAskForm(forms.ModelForm):
    class Meta():
        model = UserAsk
        fields = ['name', 'mobile', 'course_name']

    # 自定义验证写法固定，clean开头_后跟上字段名称
    def clean_mobile(self):
        mobile = self.cleaned_data['mobile']
        REGEX_MOBILE = '^1(3|4|5|7|8)\d{9}$'
        p = re.compile(REGEX_MOBILE)
        if p.match(mobile):
            return mobile
        else:
            raise forms.ValidationError('手机号非法！！！', code='mobile_invalid')

apps/organization/views.py
from django.shortcuts import render
from django.views import View
from .models import CourseOrg, CityDict, Teacher
from pure_pagination import Paginator, EmptyPage, PageNotAnInteger
from .forms import UserAskForm
from django.http import HttpResponse, JsonResponse
from operation.models import UserFavorite
from courses.models import Course


# Create your views here.
class OrganizationView(View):
    def get(self, request):
        org_list = CourseOrg.objects.all()
        all_citys = CityDict.objects.all()
        category = CourseOrg.objects.values('category').distinct()
        hot_org = CourseOrg.objects.order_by("-click_nums")[0:3]
        current_page = 'org_list'

        ct = request.GET.get('ct', '')
        city_id = request.GET.get('city', '')
        sort = request.GET.get('sort', '')
        if ct:
            org_list = org_list.filter(category=ct)
        if city_id:
            org_list = org_list.filter(address=city_id)
        if sort:
            if sort == 'students':
                org_list = org_list.order_by('-students')
            elif sort == 'courses':
                org_list = org_list.order_by('-course_nums')

        # 分页
        try:
            page = request.GET.get('page', 1)
        except PageNotAnInteger:
            page = 1
        p = Paginator(org_list, 3, request=request)
        org_page = p.page(page)
        return render(request, 'organizations/org-list.html',
                      {'org_list': org_page, 'all_citys': all_citys, 'categorys': category, 'ct': ct,
                       'city_id': city_id, 'sort': sort, 'page': page, 'hot_org': hot_org,
                       'current_page': current_page})


class UserAskView(View):
    def post(self, request):
        user_askform = UserAskForm(request.POST)
        if user_askform.is_valid():
            user_ask = user_askform.save(commit=True)
            return JsonResponse({'status': 'success'})
        else:
            return JsonResponse({'status': 'fail', 'msg': '添加出错'})


class OrgDetailHomeView(View):
    def get(self, request, org_id):
        current_page = 'home'
        org = CourseOrg.objects.get(id=org_id)
        org.click_nums += 1
        org.save()
        all_course = org.course_set.all()[:3]
        all_teacher = org.teacher_set.all()[:3]

        is_fav = False
        if request.user.is_authenticated():
            if UserFavorite.objects.filter(user=request.user, fav_id=org.id, fav_type=2):
                is_fav = True
        return render(request, 'organizations/org-detail-homepage.html',
                      {'org': org, 'current_page': current_page, 'all_course': all_course, 'all_teacher': all_teacher,
                       'is_fav': is_fav})


class OrgDetailCourseView(View):
    def get(self, request, org_id):
        current_page = 'course'
        org = CourseOrg.objects.get(id=org_id)
        is_fav = False
        if request.user.is_authenticated():
            if UserFavorite.objects.filter(user=request.user, fav_id=org.id, fav_type=2):
                is_fav = True
        return render(request, 'organizations/org-detail-course.html',
                      {'current_page': current_page, 'org': org, 'is_fav': is_fav})


class OrgDetailTeacherView(View):
    def get(self, request, org_id):
        current_page = 'teacher'
        org = CourseOrg.objects.get(id=org_id)
        is_fav = False
        if request.user.is_authenticated():
            if UserFavorite.objects.filter(user=request.user, fav_id=org.id, fav_type=2):
                is_fav = True
        return render(request, 'organizations/org-detail-teachers.html',
                      {'current_page': current_page, 'org': org, 'is_fav': is_fav})


class OrgDetailDescView(View):
    def get(self, request, org_id):
        current_page = 'desc'
        org = CourseOrg.objects.get(id=org_id)
        is_fav = False
        if request.user.is_authenticated():
            if UserFavorite.objects.filter(user=request.user, fav_id=org.id, fav_type=2):
                is_fav = True
        return render(request, 'organizations/org-detail-desc.html',
                      {'current_page': current_page, 'org': org, 'is_fav': is_fav})


class AddFavView(View):
    def post(self, request):
        fav_id = int(request.POST.get('fav_id', 0))
        fav_type = int(request.POST.get('fav_type', 0))
        if not request.user.is_authenticated():
            return JsonResponse({'status': 'fail', 'msg': '用户未登陆'})
        exist_records = UserFavorite.objects.filter(fav_id=fav_id, fav_type=fav_type)
        if exist_records:
            exist_records.delete()
            # 课程
            if fav_type == 1:
                course = Course.objects.get(id=fav_id)
                course.fav_nums -= 1
                if course.fav_nums < 0:
                    course.fav_nums = 0
                course.save()
            # 机构
            if fav_type == 2:
                course_org = CourseOrg.objects.get(id=fav_id)
                course_org.fav_nums -= 1
                if course_org.fav_nums < 0:
                    course_org.fav_nums = 0
                course_org.save()
            # 教师
            if fav_type == 3:
                teacher = Teacher.objects.get(id=fav_id)
                teacher.fav_nums -= 1
                if teacher.fav_nums < 0:
                    teacher.fav_nums = 0
                teacher.save()
            return JsonResponse({'status': 'success', 'msg': '收藏'})
        else:
            user_fav = UserFavorite()
            if fav_id > 0 and fav_type > 0:
                user_fav.fav_id = fav_id
                user_fav.fav_type = fav_type
                user_fav.user = request.user
                user_fav.save()
                # 课程
                if fav_type == 1:
                    course = Course.objects.get(id=fav_id)
                    course.fav_nums += 1
                    course.save()
                # 机构
                if fav_type == 2:
                    course_org = CourseOrg.objects.get(id=fav_id)
                    course_org.fav_nums += 1
                    course_org.save()
                # 教师
                if fav_type == 3:
                    teacher = Teacher.objects.get(id=fav_id)
                    teacher.fav_nums += 1
                    teacher.save()
                return JsonResponse({'status': 'success', 'msg': '已收藏'})
            else:
                return JsonResponse({'status': 'fail', 'msg': '收藏出错'})

templates/organizations/org-detail-course.html
{% extends 'base_org.html' %}
{% block right %}
    <div class="right companycenter layout">
        <div class="head">
            <h1>机构课程</h1>
        </div>
        <div class="brief group_list">
            {% for course in org.course_set.all %}
                <div class="module1_5 box">
                    <a class="comp-img-box" href="course-detail.html">
                        <img width="214" height="195" src="/media/{{ course.image }}"/>
                    </a>
                    <div class="des">
                        <a href="course-detail.html"><h2>{{ course.name }}</h2></a>
                        <span class="fl">课时：<i class="key">{{ course.learn_times }}</i></span>
                        <span class="fr">学习人数{{ course.students }}</span>
                    </div>
                    <div class="bottom">
                        <span class="fl">{{ org.name }}</span>
                        <span class="star fr  notlogin
                            " data-favid="13" data-fav-type="4">
                            {{ org.fav_nums }}
                        </span>
                    </div>
                </div>
            {% endfor %}

        </div>
        <div class="pageturn">
            <ul class="pagelist">
                <li class="active"><a href="?page=1">1</a></li>
            </ul>
        </div>
    </div>
{% endblock %}

templates/organizations/org-detail-desc.html
{% extends 'base_org.html' %}
{% block page_map %}<a>机构介绍</a>{% endblock %}
{% block right %}
    <div class="right companycenter layout">
        <div class="head">
            <h1>机构介绍</h1>
        </div>
        <div class="des">
            {{ org.desc }}
        </div>
    </div>
{% endblock %}

templates/organizations/org-detail-homepage.html
{% extends 'base_org.html' %}
{% block right %}
    <div class="right companycenter layout grouping">
        <div class="head">
            <h1>全部课程</h1>
            <a class="green fr more" href="org-detail-course.html">查看更多 > </a>
        </div>
        <div class="brief group_list">
            {% for course in all_course %}
                <div class="module1_5 box">
                    <a href="{% url 'course:course_detail' course.id %}"><img width="214"
                                                                              src="/media/{{ course.image }}"/></a>
                    <div class="des">
                        <a href="course-detail.html"><h2>{{ course.name }}</h2></a>
                        <span class="fl">课时：<i class="key">{{ course.learn_times }}分钟</i></span>
                        <span class="fr">参加人数：{{ course.students }}</span>
                    </div>
                    <div class="bottom">
                        <span class="fl">{{ org.name }}</span>
                        <span class="star fr  notlogin
                            " data-favid="13" data-fav-type="4">
                            {{ org.fav_nums }}
                        </span>
                    </div>
                </div>
            {% endfor %}


        </div>
    </div>
    <div class="right companycenter layout">
        <div class="head">
            <h1>机构教师</h1>
            <a class="green fr more" href="org-detail-teachers.html">查看更多 > </a>
        </div>
        {% for teacher in all_teacher %}
            <div class="diarys">
                <div class="module5 share company-diary-box" style="padding:10px 0;">
                    <div class="left">
                        <img class="pic" src="/media/{{ teacher.image }}"/>
                        <p>昵称：{{ teacher.name }}</p>
                    </div>
                    <div class="right">
                        <div class="top">
                            <div class="fl"> {% for course in teacher.course_set.all|slice:':1' %}
                                <a href=""><h1>
                                    {{ course.name }}
                                </h1>
                                </a>
                                <span>发表于：{{ course.add_time|date }}</span>
                            {% endfor %}
                            </div>
                        </div>
                        <div class="middle" style="border-bottom:0;">课程介绍</div>
                    </div>
                </div>
            </div>
        {% endfor %}

    </div>
    <div class="right companycenter layout">
        <div class="head">
            <h1>机构介绍</h1>
            <a class="green fr more" href="org-detail-desc.html">查看更多 > </a>
        </div>
        <div class="cont">&nbsp;
            {{ org.desc }}
        </div>
    </div>
{% endblock %}

templates/organizations/org-detail-teachers.html
{% extends 'base_org.html' %}
{% block right %}
    <div class="right companycenter layout">
        <div class="head">
            <h1>机构讲师</h1>
        </div>
        <div class="messagelist">
            <div class=" butler_list butler-fav-box">

                {% for teacher in org.teacher_set.all %}
                    <dl class="des users">
                        <dt>
                            <a href="">
                                <img width="100" height="100" class="scrollLoading"
                                     data-url="/media/{{ teacher.image }}"
                                     src="/media/{{ teacher.image }}"/>
                            </a>
                        </dt>
                        <dd>
                            <h1>
                                <a href="">
                                    {{ teacher.name }}<span class="key">已认证</span>
                                </a>
                            </h1>
                            <ul class="cont clearfix">
                                <li class="time">工作年限：<span>{{ teacher.work_years }}年</span></li>
                                <li class="c7">课程数：<span>{{ teacher.course_set.all.count }}</span></li>
                            </ul>
                        </dd>
                    </dl>
                {% endfor %}
            </div>
        </div>
    </div>

{% endblock %}

templates/organizations/org-list.html
{% extends 'base.html' %}

{% block title %}程机构列表 - 慕学在线网{% endblock %}
{% block content %}
    <section>
        <div class="wp butler_list_box list">
            <div class='left'>
                <div class="listoptions">
                    <ul>
                        <li>
                            <h2>机构类别</h2>
                            <div class="cont">
                                <a href="?city={{ city_id }}&sort={{ sort }}&page={{ page }}"><span
                                        {% ifequal ct '' %}class="active2"{% endifequal %}>全部</span></a>

                                {% for category in categorys %}
                                    <a href="?ct={{ category.category }}&city={{ city_id }}&sort={{ sort }}&page={{ page }}"><span
                                            {% ifequal ct category.category %}class="active2"{% endifequal %}>
                                            {% ifequal category.category 'gr' %}个人{% endifequal %}
                                        {% ifequal category.category 'pxjg' %}培训机构{% endifequal %}
                                        {% ifequal category.category 'gx' %}高校{% endifequal %}</span>
                                    </a>
                                {% endfor %}

                            </div>
                        </li>
                        <li>
                            <h2>所在地区</h2>
                            <div class="more">更多</div>
                            <div class="cont">
                                <a href="?ct={{ ct }}&sort={{ sort }}&page={{ page }}"><span
                                        {% ifequal city_id '' %}class="active2"{% endifequal %}>全部</span></a>
                                {% for city in all_citys %}
                                    <a href="?city={{ city.id }}&ct={{ ct }}&sort={{ sort }}&page={{ page }}"><span
                                            {% ifequal city_id city.id|stringformat:'i' %}class="active2"{% endifequal %}>{{ city }}</span></a>
                                {% endfor %}
                            </div>
                        </li>
                    </ul>
                </div>
                <div class="all">共<span class="key">{{ org_list.count }}</span>家</div>
                <div class="butler_list company list">
                    <div class="layout">
                        <div class="head">
                            <ul class="tab_header">
                                <li {% ifequal sort '' %}class="active"{% endifequal %}><a
                                        href="?ct={{ ct }}&city={{ city_id }}">全部</a></li>
                                <li {% ifequal sort 'students' %}class="active"{% endifequal %}><a
                                        href="?sort=students&ct={{ ct }}&city={{ city_id }}">学习人数 &#8595;</a>
                                </li>
                                <li {% ifequal sort 'courses' %}class="active"{% endifequal %}><a
                                        href="?sort=courses&ct={{ ct }}&city={{ city_id }}">课程数 &#8595;</a></li>
                            </ul>
                        </div>
                        {% for org in org_list.object_list %}
                            <dl class="des difdes">
                                <dt>
                                    <a href="{% url 'org:detail' org.id %}">
                                        <img width="200" height="120" class="scrollLoading"
                                             data-url="/media/{{ org.image }}"/>
                                    </a>
                                </dt>
                                <dd>
                                    <div class="clearfix">
                                        <a href="org-detail-homepage.html">
                                            <h1>{{ org.name }}</h1>
                                            <div class="pic fl">

                                                <img src="/static/images/authentication.png"/>

                                                <img src="/static/images/gold.png"/>

                                            </div>
                                        </a>
                                    </div>
                                    <ul class="cont">
                                        <li class="first"><p class="pic9">课程数：<span>{{ org.course_nums }}</span></p>
                                            <p class="c7">学习人数：<span>{{ org.students }}</span></p></li>
                                        <li class="c8" style="padding-left:18px;">{{ org.address }}</li>
                                        <li class="pic10" style="padding-left:18px;">经典课程：

                                            <a href="/diary/19/">c语言基础入门</a>

                                            <a href="/diary/16/">数据库基础</a>

                                        </li>
                                    </ul>
                                </dd>
                                <div class="buy start_groupbuy jsShowPerfect2" data-id="22"><br/>联系<br/>服务</div>
                            </dl>
                        {% endfor %}
                    </div>
                    <div class="pageturn">
                        <ul class="pagelist">
                            {% if org_list.has_previous %}
                                <li class="long"><a href="?city={{ city.id }}&ct={{ ct }}&sort=
                                        {{ sort }}{{ org_list.previous_page_number.querystring }}">上一页</a>
                                </li>
                            {% endif %}
                            {% for page in org_list.pages %}
                                {% if page %}
                                    {% ifequal page org_list.number %}
                                        <li class="active"><a
                                                href="?city={{ city.id }}&ct={{ ct }}&sort={{ sort }}&page={{ page }}">{{ page }}</a>
                                        </li>
                                    {% else %}
                                        <li>
                                            <a href="?city={{ city.id }}&ct={{ ct }}&sort={{ sort }}&page={{ page }}">{{ page }}</a>
                                        </li>
                                    {% endifequal %}
                                {% endif %}
                            {% endfor %}

                            {% if org_list.has_next %}
                                <li class="long"><a href="?city={{ city.id }}&ct={{ ct }}&sort=
                                        {{ sort }}{{ org_list.next_page_number.querystring }}">下一页</a>
                                </li>
                            {% endif %}

                        </ul>
                    </div>
                </div>
            </div>
            <div class="right companyright">
                <div class="head">我要学习</div>
                <form class="rightform" id="jsStayForm">
                    <div>
                        <img src="/static/images/rightform1.png"/>
                        <input type="text" name="name" id="companyName" placeholder="名字" maxlength="25"/>
                    </div>
                    <div>
                        <img src="/static/images/rightform2.png"/>
                        <input type="text" name="mobile" id="companyMobile" placeholder="联系电话"/>
                    </div>
                    <div>
                        <img src="/static/images/rightform3.png"/>
                        <input type="text" name="course_name" id="companyAddress" placeholder="课程名" maxlength="50"/>
                    </div>
                    <p class="error company-tips" id="jsCompanyTips"></p>
                    <input class="btn" type="text" id="jsStayBtn" value="立即咨询 >"/>
                    {% csrf_token %}
                </form>
            </div>

            <div class="right companyrank layout">
                <div class="head">授课机构排名</div>

                {% for hot in hot_org %}
                    <dl class="des">
                        <dt class="num fl">1</dt>
                        <dd>
                            <a href="{% url 'org:detail' hot.id %}"><h1>{{ hot.name }}</h1></a>
                            <p>{{ hot.address }}</p>
                        </dd>
                    </dl>
                {% endfor %}
            </div>
        </div>
    </section>
{% endblock %}
{% block js %}

    <script>
        $(function () {
            $('#jsStayBtn').on('click', function () {
                $.ajax({
                    cache: false,
                    type: "POST",
                    url: "/org/add_ask/",
                    data: $('#jsStayForm').serialize(),
                    async: true,
                    success: function (data) {
                        if (data.status == 'success') {
                            $('#jsStayForm')[0].reset();
                            $('#jsCompanyTips').html("")
                            alert("提交成功")
                        } else if (data.status == 'fail') {
                            $('#jsCompanyTips').html(data.msg)
                        }
                    },
                });
            });
        })

    </script>
{% endblock %}